apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=./Dockerfile"
        - "--context=s3://kjhkanikotest/context.tar.gz"
        - "--destination={AWS_ACCOUND_ID}.dkr.ecr.us-east-2.amazonaws.com/kanikodemo:v1"
      env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
        - name: AWS_REGION
          value: us-east-2
  restartPolicy: Never